### ISSUE TITLE
Selection of the same chemical multiple times possible

### ISSUE THREAD

**Issue by kathi208** [Calciumdibromid/CaBr2#108]
It is possible to select one chemical more than once and add it to the list underneath.
![Bildschirmfoto vom 2021-02-14 00-50-00](https://user-images.githubusercontent.com/74504874/107864653-b1914180-6e5e-11eb-9fda-8f314b8997fd.png)

**Comment by crapStone** [comment]
I would add a simple check if the `cas`-number is already in the list.

**Comment by crapStone** [comment]
blocked by #114
