### ISSUE TITLE
Add "Anleitung anschauen" - menu button

### ISSUE THREAD

**Issue by kathi208** [Calciumdibromid/CaBr2#113]
![Bildschirmfoto vom 2021-02-14 01-22-18](https://user-images.githubusercontent.com/74504874/107865092-7ba28c00-6e63-11eb-90bb-fa962f02c070.png)

**Comment by crapStone** [comment]
add button and menu

**Comment by Epsilon02** [comment]
Is there another issue to get the data from the backend?

**Comment by crapStone** [comment]
See #214
