### ISSUE TITLE
Showcase Removal Notice

### ISSUE THREAD

**Issue by JonasKruckenberg** [Calciumdibromid/CaBr2#1144]
Hello friends of Tauri,
With the upcoming v1 release and accompanying overhaul of the https://tauri.studio website, we will be removing the showcase section in favor of [**Awesome Tauri**](https://github.com/tauri-apps/awesome-tauri). 
If you want to keep your project featured, please submit it to that list instead, but please note the rules for submissions have changed.

Thank you for all your support in getting Tauri to this point!

Jonas,
the Tauri team

**Comment by JonasKruckenberg** [comment]
I tried creating an account at codeberg without success, so I hope you still see this here

**Comment by 6543** [comment]
@JonasKruckenberg thanks we do :)

That you could not create an account is definetly an issue, that should be fixed, I'll report that to codeberg.

**Comment by JonasKruckenberg** [comment]
Yeah I trued to connect my Github account and that didn't wirk at all.

**Comment by JonasKruckenberg** [comment]
Ooh well okay that explains it 😅 thanks!

**Comment by 6543** [comment]
https://github.com/tauri-apps/awesome-tauri/pull/21
