### ISSUE TITLE
Enable caching for faster CI

### ISSUE THREAD

**Issue by Epsilon02** [Calciumdibromid/CaBr2#149]
Maybe this is a good idea: https://github.com/marketplace/actions/npm-or-yarn-install-with-caching

Also it is a good thing to use `yarn install --frozen-lockfile` for CI.

**Comment by Epsilon02** [comment]
Found something for Rust too: https://github.com/marketplace/actions/rust-cache

**Comment by crapStone** [comment]
I would add a Dockerfile for a custom container so that we can skip the update process on each run.

**Comment by 6543** [comment]
closed by  #179
