### ISSUE TITLE
Unsubscribe observables on component destroy

### ISSUE THREAD

**Issue by Epsilon02** [Calciumdibromid/CaBr2#191]
To prevent memory leaks subscriptions must be unsubscribed when competent is destroyed
This issue depends on #164

**Comment by 6543** [comment]
@Epsilon02 state?

**Comment by crapStone** [comment]
will be fixed by #848

**Comment by Epsilon02** [comment]
As soon as #1048 is merged I will check if there is any additional work to do here.

**Comment by 6543** [comment]
merged
