### ISSUE TITLE
Ideas for data providers

### ISSUE THREAD

**Issue by 6543** [Calciumdibromid/CaBr2#218]
* [ ] Avantor
 * [ ] Carl Roth
 * [ ] [echa](https://echa.europa.eu/de/information-on-chemicals/cl-inventory-database)
 * [x] Gestis
 * [ ] Degintu (#15)
 * [ ] MERCK (#81)
 * [ ] TCI Chemicals
 * [ ] VWR
 * [ ] ZEFA
 * [ ] PubChem (#393)

**Comment by crapStone** [comment]
see #81 #15
