### ISSUE TITLE
make editing visible in the preview and on the pdf

### ISSUE THREAD

**Issue by kathi208** [Calciumdibromid/CaBr2#248]
- [ ] It might be good to mark every changed detail with italic font on the pdf and in the preview
- [ ] add info in the line of sources what italic means

**Comment by crapStone** [comment]
duplicate of #207?

**Comment by kathi208** [comment]
No, there's a difference between an edited-symbol next to a chemical in the list underneath the search or a cursive text in the preview and on the pdf, when context has been changed.
