### ISSUE TITLE
replace google fonts with own

### ISSUE THREAD

**Issue by 6543** [Calciumdibromid/CaBr2#28]

**Comment by crapStone** [comment]
why?

**Comment by 6543** [comment]
privacy

**Comment by crapStone** [comment]
When the project is built in release mode all dependencies are downloaded and packaged locally.
Our frontend-application can't even make requests if it wanted to, I disabled this in the tauri config.

**Comment by 6543** [comment]
sure I know it's just not nice for devs ... would say low prio but it's a bad habbit in my eyes ...

**Comment by Epsilon02** [comment]
I don't understand the problem with a font? Its Roboto Font which works well with Material Design (also from google) and as @crapStone mentioned all dependencies are packaged locally.
