### ISSUE TITLE
Update Translations via CI

### ISSUE THREAD

**Issue by 6543** [Calciumdibromid/CaBr2#309]
- push en_us.json to crowdin if changed
- pull translations from crowdin & commit if something changed

TODO:
 * [x] create update script (#368)
 * [x] create docker image with `crowdin` cli tool & `nodejs` exec script in CI
 * [x] add secrets & task to CI (#466)

**Comment by 6543** [comment]
-> #368 ...

**Comment by crapStone** [comment]
do not circumvent protection, create a task that runs daily/weekly that creates a PR with changes

**Comment by 6543** [comment]
-> split into two tasks

1. one who uploade on merge
2. nightly task who create pull if changes exist to apply
