### ISSUE TITLE
Add endpoint for getting and saving templates

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#339]
Add an endpoint for getting and storing CaBr2Document templates.

**Comment by 6543** [comment]
do we need a special template format, since you can create "templates" by creating a new unfinished document and if you need it just open, eddit & save as a new one ...

**Comment by crapStone** [comment]
My idea is, that we can ship some default templates and that the user can save a partially filled document with less clicks an in a pre-specified folder.
This way we can also add a setting to select a template to autoload on startup.
