### ISSUE TITLE
Hall of failure (Gestis parser )

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#344]
These substances fail to parse with the current parser.
Add test with the new parser!

- [535641](https://gestis.dguv.de/data?name=535641)

**Comment by kathi208** [comment]
I noticed that the molecular mass is only not added, when you search directly for a element, e.g. Na

**Comment by crapStone** [comment]
This is not used. Please open a new issue for every gestis failure you encounter.
