### ISSUE TITLE
Clear description line when openting a new sheet

### ISSUE THREAD

**Issue by kathi208** [Calciumdibromid/CaBr2#429]
**Describe the bug**
When opening a new sheet, the line for the description of the experiment is not cleared

**To Reproduce**
make a safety sheet and fill all the gaps.
then open a new sheet
all the gaps will be empty (headers excluded) 

**Expected behavior**
it would be good to clear the description line for the experiment, because this information will change everytime when I create a new safety sheet

**Comment by Epsilon02** [comment]
It also does not work for all the other inputs in the first card.

**Comment by kathi208** [comment]
But those should stay there.

Only the description line should be cleared.
