### ISSUE TITLE
If an error occurs when opening files no error is displayed

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#445]
Add an error snackbar when a file fails to open

**Comment by Epsilon02** [comment]
@crapStone can't reproduce, I got an alert and this line is responsible and working. https://github.com/Calciumdibromid/CaBr2/blob/d868075cb5ad438f0e46f75536dc7089d62df39f/src/app/menubar/menubar.component.ts#L131
I will leave this issue open in case you mean another case. If that so, so please add a description to reproduce this issue.

**Comment by Epsilon02** [comment]
> @crapStone can't reproduce, I got an alert and this line is responsible and working.
> 
> https://github.com/Calciumdibromid/CaBr2/blob/d868075cb5ad438f0e46f75536dc7089d62df39f/src/app/menubar/menubar.component.ts#L131
> 
> I will leave this issue open in case you mean another case. If that so, so please add a description to reproduce this issue.

ping @crapStone

**Comment by crapStone** [comment]
should be fixed
