### ISSUE TITLE
Merge webapp and this repo

### ISSUE THREAD

**Issue by 6543** [Calciumdibromid/CaBr2#467]
add changes of https://github.com/Calciumdibromid/cabr2_webapp to be able to build a webapp **or** the tauri app

- [x] rewrite handlers to comply with wasm restrictions
- [x] add `webserver.rs` files and `webserver` feature to all crates
- [x] rewrite frontend code inspired by webapp frontend hacks
- [x] archive webapp repo

**Comment by crapStone** [comment]
blocked by #505 #506

**Comment by crapStone** [comment]
blocked by #537 #538 #539
