### ISSUE TITLE
Add location and date to signature 

### ISSUE THREAD

**Issue by kathi208** [Calciumdibromid/CaBr2#468]
- [x] preview
- [x] pdf

**Comment by kathi208** [comment]
It would be good to add "date" and "location" to the signature fields in the preview and pdf.

So when you and the assistant signs the pdf, they have to write down where they signed it and when. It looks more official.

**Comment by Epsilon02** [comment]
There is a possible problem with wkhtml2pdf. The additional styling to move the location-date-signature to the bottom-right of a cell move it to the last right cell. In my opinion we should save this for the new PDF generation.
