### ISSUE TITLE
comply to DSGVO

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#498]

**Comment by 6543** [comment]
we mostly do, just for webapp write down: we temporary store generated pdf for few minits & the ip get loged & periodicaly deleted ...

**Comment by 6543** [comment]
Jup

**Comment by 6543** [comment]
yes ....

**Comment by crapStone** [comment]
We decided that we don't need any of this because the website is hosted by a single person (/private entity)
