### ISSUE TITLE
make handler abstraction with inlining

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#506]

**Comment by crapStone** [comment]
blocks #467

**Comment by crapStone** [comment]
@6543  do we really need this?
The compiler can inline these functions itself and probably does a better job than we will (https://stackoverflow.com/a/52297790).

**Comment by 6543** [comment]
https://github.com/Calciumdibromid/CaBr2/blob/develop/src-tauri/Cargo.toml#L74

We have LZO so we just need to set profile to "03", and this should close it ...?

**Comment by crapStone** [comment]
That is already the default for this profile: https://doc.rust-lang.org/cargo/reference/profiles.html#release

**Comment by 6543** [comment]
ahah ok lets loks it by ref: https://doc.rust-lang.org/cargo/reference/profiles.html#release
