### ISSUE TITLE
rewrite data provider interface

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#526]

**Comment by crapStone** [comment]
@Epsilon02 do you still remember our ideas on that?

**Comment by Epsilon02** [comment]
> @Epsilon02 do you still remember our ideas on that?

Well... no 😅
We should brainstorm about this maybe we get the ideas again.

**Comment by 6543** [comment]
I think we can close it and if we add a second, third, ... provider we will notice what has to change
