### ISSUE TITLE
Add web-only frontend code inspired by webapp frontend hacks

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#539]
blocks #467 

- [x] Add build target in angular.json
- [x] Create custom environment.web.ts
- [x] Bootstrap services
- [x] Modify Dependency Injections of Services in Components
- [x] Implement Services for Web Build Target (Blocked by #649 )

**Comment by Epsilon02** [comment]
- [ ] Add build target in angular.json
- [ ] Create custom environment.web.ts
- [ ] Bootstrap services
- [ ] Modify Dependency Injections of Services in Components

**Comment by crapStone** [comment]
@Epsilon02 is this really done?

**Comment by Epsilon02** [comment]
It was GitHub actions not me 😅
PR is still open
I will reopen this issue at the evening
