### ISSUE TITLE
Replace lodash.merge with something else.

### ISSUE THREAD

**Issue by Epsilon02** [Calciumdibromid/CaBr2#545]
I got a warning from Angular that libraries they depend on commonjs are responsible for large bundle sizes.
Got following Output from Angular CLI:
```
Warning: CaBr2/src/app/@core/services/i18n/i18n.service.ts depends on 'lodash'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
We should think about another solution for this case.
Found following solutions:
 - this whole [SO-Entry](https://stackoverflow.com/questions/27936772/how-to-deep-merge-instead-of-shallow-merge)
 - [deepmerge](https://www.npmjs.com/package/deepmerge) last update 2 years ago
 - [merge-json-file](https://www.npmjs.com/package/merge-json-file) 7 months ago
 - [ts-deepmerge](https://www.npmjs.com/package/ts-deepmerge) last update 6 days ago
 status 05/17/21

**Comment by 6543** [comment]
fixed by #801
