### ISSUE TITLE
invalid args for command `save_document`: invalid type: integer `3`, expected string or map

### ISSUE THREAD

**Issue by 6543** [Calciumdibromid/CaBr2#546]
**Describe the bug**
Can not save **cab2** file error msg: `invalid args for command `save_document`: invalid type: integer `3`, expected string or map`

**To Reproduce**
1. create new datasheet
2. add `bananenöl`
3. add `32`as Quantity with Unit `g` 
4. try to save

**Comment by 6543** [comment]
tld: unit enum's are not matched correctly

**Comment by 6543** [comment]
bug still exist!

**Comment by crapStone** [comment]
could not reproduce, it probably was fixed with #649
