### ISSUE TITLE
Draw bugreport/feedback button

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#60]

**Comment by kathi208** [comment]
Icon is ready
It has to be added to the program now.

**Comment by Epsilon02** [comment]
Where should the icon be in the UI

**Comment by kathi208** [comment]
Bottom left? In the bar where all the other icons are?

Maybe above the version number?

**Comment by kathi208** [comment]
just link the email: cabr2.help@gmail.com
