### ISSUE TITLE
Telemetry server

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#62]
Write a telemetry server that receives fails from Gestis, bug reports and feedback messages from the clients.

**Comment by 6543** [comment]
cc @crapStone 
```rust
struct Entry {
    ID: i32
    Level: u8
    Version: String
    Content: String
}
```

**Comment by crapStone** [comment]
```rust
struct Entry {
    id: u32,
    version: String,
    content: Content,
}

enum Type {
    Error {
        message: String,
    },
    Feedback {
        contact: String,
        message: String,
    },
    Bugreport {
        contact: String,
        message: String,
   },
    Gestis { // needed?
        error: String,
        zvg_number: String,
    }
}
```

**Comment by crapStone** [comment]
wait for tauri betarelease

**Comment by 6543** [comment]
> ```rust
> ...
> enum Content {
> ...
>     Gestis {
>         error: String,
>         zvg_number: String,
>     }
> }
> ```

I think we should not hard code providers

**Comment by crapStone** [comment]
I think `error` should have it's own enum.
That way we can send different levels of information with different errors and can extend it in the future.
