### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#758]
Move everything into dedicated subfolders e.g. `frontend` and `backend`.

Structure the rust part of the project like described here: https://matklad.github.io/2021/08/22/large-rust-workspaces.html

**Comment by 6543** [comment]
I dont think we have to do this, because:
* it wont add value (just move already structured code)
* it's already well structured
* we would differ from other tauri projects
* it wint improve documentation or similar to get used to codebase

**Comment by 6543** [comment]
tld: 😆 there are real issues to solve

**Comment by crapStone** [comment]
Have a look at my draft PR with the wasm stuff. The Project isn't well structured and it gets worse with every new feature.

**Comment by Epsilon02** [comment]
Per se I am with @6543 , but I saw in your PR @crapStone  what you mean.
Maybe a rough example how the new structure should be look like would be helpful for a decision.

**Comment by 6543** [comment]
ping
