### ISSUE TITLE
Add tests framework/ci

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#8]
Add tests for front- and backend.
 * [x] Linter JS
 * [ ] Unit tests JS 
 * [x] Linter Rust
 * [x] Unit tests Rust
 * [ ] Integrationtests
 * [x] ~~Editorconfig Check~~ -> Prettier Check

**Comment by 6543** [comment]
I think the first steps would be to add linter for JS and Rust

**Comment by crapStone** [comment]
Linting and tests in Rust is easy

- linting: `cargo clippy` should return without warnings
- tests: `cargo test` should return successfully

**Comment by 6543** [comment]
ok with this info I'm able to add ci for rust

**Comment by crapStone** [comment]
@6543 what about the other checks?

**Comment by 6543** [comment]
wip ...
