### ISSUE TITLE
Improve READMEs

### ISSUE THREAD

**Issue by Batman089** [Calciumdibromid/CaBr2#976]
**General**
At the first thank you for your passionate work. I tried to run this project on different OSs. At the very beginning I struggled with installing packages and dependencies. Some of them were recognized by IDE or OS-package manager but the project doesn't run. I see there is a beautiful readme in the project but these is way far from being complete.  

**README for Windows 10**
After struggling for more than for days I gave up to run and configure this project on windows 10. And then I tried to run it on Linux-Fedora-kernel.

**README for Linux**
I tried to run it on Fedora with Intellij Community version. Surprisingly it didn't go well. I invest only one day to build it. For sure there are some developers, that could run and build the project easily but I guess a detailed README with some information about packages and start-confs could help all other developers.

**Comment by crapStone** [comment]
- [ ] add examples for packages that need to be installed
- [ ] better / more detailed information on how to run it
- [ ] more detailed (different for frontend and backend) explanation for development
- [ ] ...
