### ISSUE TITLE
show popup with reasons that block the user from saving

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#99]
In the edit substance dialog the user doesn't know the reason that prevents them from saving.
Proposal: scroll to input with error

Example: CobaltNitrat

**Comment by kathi208** [comment]
or at least show a message why you can not save the chemical after editing it for now!
if you have no idea why it is not working, it takes a while until you scroll down and see the "wrong" h-phrases

it would be helpful to see immediately why you can not save the chemical

(I had the problem with "cyanwasserstoff")

**Comment by crapStone** [comment]
need info dialog first
